export const ui = {
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    FETCH_PAGE_COMPONENTS: "FETCH_PAGE_COMPONENTS"
}
export const search = {
    SEARCH_BY_QUERY: "SEARCH_BY_QUERY"
}
export const product = {
    FETCH_PRODUCT: "FETCH_PRODUCT",
    FETCH_PRODUCTS_BY_CATEGORY: "FETCH_PRODUCTS_BY_CATEGORY"
}

export const cart = {
    FETCH_CART: "FETCH_CART"
}

export const checkout = {
    CHECKOUT_ACTION_COMPLETE: "CHECKOUT_ACTION_COMPLETE",
    SELECT_ADDRESS: "SELECT_ADDRESS",
    TOGGLE_ADDRESS_FORM: "TOGGLE_ADDRESS_FORM"
}

export const account = {
    FETCH_ADDRESS_LIST: "FETCH_ADDRESS_LIST",
    SAVE_ADDRESS: "SAVE_ADDRESS"
}

export const auth = {
    LOGIN: "LOGIN"
}